### ISSUE TITLE
Preview maps pan too easily

### ISSUE THREAD

**Issue by andywalz** [flatrockgeo/solar-suitability-app#35]
on mobile or trackpad I find I'm panning the maps unintentionally when trying to scroll down on the report. Could your same limitExtent feature be applied on these maps?

**Comment by cmartin616** [comment]
We can do that but it doesn't allow for much in the way of adjusting the point, if necessary.  We should think about what clicks we should allow and what functionality should be allowed.

**Comment by andywalz** [comment]
Let's disable panning completely and allow zooming but lock the two maps so they zoom together. Sound ok?

**Comment by andywalz** [comment]
I locked out all panning. Zomming allowed only with +/- and I think it works. If you disagree let me know.
