### ISSUE TITLE
Check percent source for progress bar and optimal/poor

### ISSUE THREAD

**Issue by andywalz** [flatrockgeo/solar-suitability-app#50]
Hey where does the 78% on the progress bar get set? 
I think that it either needs to use annualPercentSun or the Optimal/Poor case statement needs to use whatever 78% comes from (cuz 78% should be Fair, not optimal)
Ok, I found this and see how it is done but I may need your help explaining the first line: // Populate gradient
       var gradient = ((app.query.averagePerDay/4).toFixed(2)*100).toFixed().toString() + '%';
       
       var $showGradient = $('.showGradient');
       $showGradient.css('width', gradient);
       $('.showGradient>span').text(gradient);
why divide by 4?

![image](https://cloud.githubusercontent.com/assets/6788271/11314042/8cf4df58-8fa7-11e5-96a3-ead27b54dc78.png)

**Comment by cmartin616** [comment]
I don't know what I was thinking.  :)  I'm wondering if this was legacy code from testing that I didn't update.  Can you try it out now with the solarReportFixes branch?  It is *really* hard to find a location that isn't optimal or poor but it seems to be working with those two test cases.

**Comment by andywalz** [comment]
I pulled solarReportFixes just now but I don't see anything different from my branch yesterday. Am I missing something?
