### ISSUE TITLE
Solar calculator user input values causing preview maps and charts to disappear

### ISSUE THREAD

**Issue by andywalz** [flatrockgeo/solar-suitability-app#56]

**Comment by cmartin616** [comment]
This is caused by the model updating and the report re-rendering.  It has two empty div containers for the map so it renders them empty.  I'm going to have to research how to skip the divs if they are full or how to re-apply a map object to a div.

**Comment by andywalz** [comment]
Chris- what if we never close the report? Wouldn't that make this easier to resolve? I'm thinking simply hide the text (site name, site notes) and show form fields instead right in their place with save button that stores values in object and then reshows text using values? Then we don't have to worry about reloading maps/other data. I could work on this if you think this approach would work. Of all issues I'd like to fix this one for demo tomorrow....

**Comment by andywalz** [comment]
I fixed this with a work around. I like the UI behavior of the fix better but the code behind it is hacky. I'm using jquery to manually update the modal and directly change the model values because when using .set() and the render function it closed the modal on me and I couldn't figure out why or how to keep it open.

**Comment by cmartin616** [comment]
pull request #64
