### ISSUE TITLE
Reset report (site details) if new query is run

### ISSUE THREAD

**Issue by cmartin616** [flatrockgeo/solar-suitability-app#63]
Have to determine the best way to check for a new query -or- add a button to reset the report.  Thoughts?  For example, site title is 'Chris' House' but then I move onto 'Andy's House' - do I want it to show the stored values 'Chris' House' or 'Site Title'?

a) Last Lat/Lng for a click stored.  If Lat/Long when opening report =/= last Lat/Lng, reset details.  May be an issue if they just adjust their query point to a different point on the roof.

b) Always leave details unless they reset it.

**Comment by andywalz** [comment]
I like option b or maybe auto reset if distance between last/current point is greater than 1/4 mi

**Comment by andywalz** [comment]
Maybe a reset button in edit under form fields or little icon next to customize button a good idea too. Whatever you think.

**Comment by cmartin616** [comment]
I think I might just do nothing with this.  What do you think?  It would be a huge check to see if anything has changed to show a reset button.  And I'm not sure where we should show it anyway.

**Comment by andywalz** [comment]
Agreed. Let’s do nothing for now, we may be trying to solve a problem that doesn’t exist.
